services:
  sshkeys:
    image: "goffinf/infra_ssh_files:000002"
    # image: "goffinf/infra_ssh_files:000003"
    container_name: "ssh-keys-locale"
    restart: "no"
    volumes:
      - ansible_ssh_keys_root:/root/.ssh:ro
      - ansible_ssh_keys_ansible:/home/ansible/.ssh:ro
    command: sleep infinity
  ansible-nossh:
    image: "ubuntu:22.04"
    container_name: "ssh-test"
    restart: "unless-stopped"
    # entrypoint: ["sleep", "infinity"]
    command: [ "sleep", "infinity" ]
    volumes:
      - ansible_ssh_keys_root:/root/.ssh
      - ansible_ssh_keys_ansible:/home/ansible/.ssh
      # # - /home/goffinf/.ssh:/root/.ssh:ro
      # # - /home/goffinf/.ssh:/home/ansible/.ssh:ro
      # # - /c/Data/homelab/wsl2/ansible:/data
      # # - /c/Data/homelab/wsl2/ansible:/workspaces:cached
volumes:
  ansible_ssh_keys_ansible:
    name: ansible_ssh_keys_ansible
  ansible_ssh_keys_root:
    name: ansible_ssh_keys_root
