services:
  terraform:
    image: "ghcr.io/goffinf/terraform:${TERRAFORM_VERSION}-unpacked"
    container_name: "terraform"
    restart: "no"
    # restart: "unless-stopped"
    # command: [ "sleep", "infinity" ]
    # user: ${ANSIBLE_USER:-ansible}
    user: root
    volumes:
      - terraform_cli:/terraform
      - terraform_providers:/usr/share/terraform/plugins
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_BASE_IMAGE_TAG: ${ALPINE_BASE_IMAGE_TAG}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        TERRAFORM_MIRROR_FILENAME: ${TERRAFORM_MIRROR_FILENAME}
        MAINTAINER: ${MAINTAINER}
    network_mode: none
  terraform_test:
    image: "alpine:latest"
    container_name: "terraform-test"
    restart: "unless-stopped"
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     echo "Copying Terraform CLi and providers"
    #     cp /terraform/terraform /usr/local/bin/terraform
    #     cp -Rf /usr/share/terraform/plugins /usr/local/share/terraform
    command: [ "sleep", "infinity" ]
    user: root
    volumes:
      - terraform_cli:/usr/local/bin
      - terraform_providers:/usr/local/share/terraform/plugins
    network_mode: none
volumes:
  terraform_cli:
    name: terraform_cli
  terraform_providers:
    name: terraform_providers