services:
  sshkeys:
    image: "goffinf/infra_ssh_files:000002"
    # image: "goffinf/infra_ssh_files:000003"
    profiles:
    - nossh
    container_name: "ssh-keys-locale"
    restart: "no"
    volumes:
      #- ssh_keys_root_locale:/root/.ssh:ro
      #- ssh_keys_ansible_locale:/home/ansible/.ssh:ro
      - ..:workspaces:cached
    command: sleep infinity
  # ansible-nossh:
    # image: goffinf/ansible:nossh-locale-000001
    # # image: goffinf/ansible:nossh-locale-${ANSIBLE_BUILD_ID}
    # profiles:
    # - nossh
    # container_name: "ansible-nossh-locale"
    # restart: "unless-stopped"
    # #entrypoint: ["sleep", "infinity"]
    # #command: [ "sleep", "infinity" ]
    # user: ${ANSIBLE_USER:-ansible}
    # volumes:
      # # - /home/goffinf/.ssh:/root/.ssh:ro
      # # - /home/goffinf/.ssh:/home/ansible/.ssh:ro
      # - ssh_keys_root_locale:/root/.ssh:ro
      # - ssh_keys_ansible_locale:/home/ansible/.ssh:ro
      # # - ssh_keys_ansible_locale:/home/goffinf/.ssh:ro
      # # - /c/Data/homelab/wsl2/ansible:/data
      # # - /c/Data/homelab/wsl2/ansible:/workspaces:cached
    # #environment:
    # #  USER: ${ANSIBLE_USER:-ansible}
    # build:
      # context: .
      # dockerfile: Dockerfile-locale-nossh
      # args:
        # ANSIBLE_GID: ${ANSIBLE_GID}
        # ANSIBLE_UID: ${ANSIBLE_UID}
        # ANSIBLE_USERNAME: ${ANSIBLE_USERNAME}
        # CYTOPIA_IMAGE_TAG: ${CYTOPIA_IMAGE_TAG}
        # GOFFINF_SSH_FILES_IMAGE_TAG: ${GOFFINF_SSH_FILES_IMAGE_TAG}
        # LOCALE_LANG: ${LOCALE_LANG}
        # MAINTAINER: ${MAINTAINER}
        # SSH_INCLUDE_KEYS: false
        # SSH_KEYPAIR_ROOT_NAME: ${SSH_KEYPAIR_ROOT_NAME}
    # working_dir: /data
volumes:
  ssh_keys_root_locale:
  ssh_keys_ansible_locale: