services:
  ext-volume-test:
    image: "ubuntu:22.04"
    container_name: "ext-vol-test"
    restart: "unless-stopped"
    command: [ "sleep", "infinity" ]
    volumes:
      - ssh_keys_root_locale:/root/.ssh
      - ssh_keys_ansible_locale:/home/ansible/.ssh
volumes:
  ssh_keys_root_locale:
    external: true
    name: ansible_ssh_keys_root_locale
  ssh_keys_ansible_locale:
    external: true
    name: ansible_ssh_keys_ansible_locale
