services:
  sshkeys:
    image: "goffinf/infra_ssh_files:000002"
    # image: "goffinf/infra_ssh_files:000003"
    container_name: "ssh-keys-locale"
    restart: "no"
    volumes:
      - ssh_keys_root_locale:/root/.ssh:ro
      - ssh_keys_ansible_locale:/home/ansible/.ssh:ro
    command: sleep infinity
  ansible-nossh:
    image: "ubuntu:22.04"
    container_name: "ssh-test"
    restart: "unless-stopped"
    # entrypoint: ["sleep", "infinity"]
    command: [ "sleep", "infinity" ]
    volumes:
      - ssh_keys_root_locale:/root/.ssh
      - ssh_keys_ansible_locale:/home/ansible/.ssh
      # # - /home/goffinf/.ssh:/root/.ssh:ro
      # # - /home/goffinf/.ssh:/home/ansible/.ssh:ro
      # - ssh_keys_root_locale:/root/.ssh:ro
      # - ssh_keys_ansible_locale:/home/ansible/.ssh:ro
      # # - ssh_keys_ansible_locale:/home/goffinf/.ssh:ro
      # # - /c/Data/homelab/wsl2/ansible:/data
      # # - /c/Data/homelab/wsl2/ansible:/workspaces:cached
volumes:
  ssh_keys_root_locale:
  ssh_keys_ansible_locale:
