name: WSL Config

on:
    workflow_dispatch:
jobs:
  configure_wsl2:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: GHCR_Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: BUILD_and_RUN_devContainer
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     push: always
      #     imageName: ghcr.io/goffinf/wsl2-config
      #     imageTag: "0.1.0"
      #     runCmd: ansible --version

      - name: RUN_devContainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: "ghcr.io/goffinf/wsl2-config:0.1.0"
          # runCmd: pwd # /workspaces/wsl2/ansible
          runCmd: ls -al
          # runCmd: ansible --version