name: WSL Config

on:
  workflow_dispatch:
    inputs:
      ansible_ssh_keys_volume_recreate:
        description: "Whether to recrate the ansible ssh_keys volume"
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'
      ansible_ssh_keys_volume_name:
        description: "The name of docker volume from which Ansible ssh_keys will be provided"
        required: false
        type: string
        default: "ansible_ssh_keys_ansible"
      ansible_debug_mode:
          description: "Run Ansible with --check --diff"
          type: choice
          options:
            - 'true'
            - 'false'
          default: 'false'
      dev_container_image_name:
        description: "The NAME of the dev container image"
        required: false
        type: string
        default: "ghcr.io/goffinf/wsl2-config"
      dev_container_image_version:
        description: "The VERSION of the dev container image"
        required: false
        type: string
        default: "0.4.0"
jobs:
  configure_wsl2:
    permissions:
      contents: read
      packages: write
    runs-on:
      labels: wsl2
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show checkout contents
        run: |
          ls -alR ${{ github.workspace }}

      - name: GHCR_Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: recreate_ansible_ssh_keys_volume
      #   id: recreate_ansible_ssh_keys_volume
      #   if: inputs.ansible_ssh_keys_volume_recreate == 'true'
      #   run: |
      #     echo "Removing docker volume ${{ inputs.ansible_ssh_keys_volume_name }}"
      #     docker volume rm ${{ inputs.ansible_ssh_keys_volume_name }} || true

      - name: create_ansible_ssh_keys_volume
        id: create_ansible_ssh_keys_volume
        run: |
          docker volume ls
          # check volume doesn't already exist
          VOL=$(docker volume ls -f name=${{ inputs.ansible_ssh_keys_volume_name }} --format='{{.Name}}')
          echo "VOL = $VOL"
          if [ -z "$VOL" ]; then
            echo "docker volume ${{ inputs.ansible_ssh_keys_volume_name }} does NOT exist ... creating"
            docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml up --remove-orphans --detach
            # clean up stopped container but NOT the volumes
            docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml down --remove-orphans
          else
            echo "docker volume ${{ inputs.ansible_ssh_keys_volume_name }} already exists"
            if [ ${{ inputs.ansible_ssh_keys_volume_recreate }} == 'true' ]; then
              echo "re-creating the docker volume ${{ inputs.ansible_ssh_keys_volume_name }}"
              # docker volume rm ${{ inputs.ansible_ssh_keys_volume_name }} || true
              docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml down --remove-orphans --volumes
              docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml up --remove-orphans --detach
              # clean up stopped container but NOT the volumes
              docker compose -f ./ansible/docker-compose-ansible-ssh-keys.yml down --remove-orphans
            fi
          fi;
          docker volume ls

      # - name: BUILD_and_RUN_devContainer
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     push: always
      #     imageName: ghcr.io/goffinf/wsl2-config
      #     imageTag: "0.1.0"
      #     runCmd: ansible --version

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: RUN_devContainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          cacheFrom: "${{ inputs.dev_container_image_name }}:${{ inputs.dev_container_image_version }}"
          configFile: "./.devcontainer/gha/devcontainer.json"
          runCmd: |
            terraform version
            pwd
            GITHUB_REPOSITORY="${{ github.repository }}"
            echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
            GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY#*/}"
            echo "GITHUB_REPOSITORY_NAME = $GITHUB_REPOSITORY_NAME"
            echo "GITHUB_WORKSPACE = ${{ github.workspace }}"
            cd /tmp
            git clone "https://github.com/${GITHUB_REPOSITORY}.git"
            cd "${GITHUB_REPOSITORY_NAME}/ansible"
            ls -al
            echo "Show Anisible version"
            ansible --version
            # if [ ${{ inputs.ansible_debug_mode }} == 'true' ]; then
            #   echo "Running the Ansible playbook in debug mode"
            #   ansible-playbook main.yml --check --diff
            # else
            #   echo "Running the Ansible playbook"
            #   ansible-playbook main.yml
            # fi
            echo "Removing git repo"
            rm -rf "/tmp/${GITHUB_REPOSITORY_NAME}"

      # - name: Clean up repo
      #   run: |
      #     echo "Removing git repo"
      #     rm -rf "/tmp/${GITHUB_REPOSITORY_NAME}"

# 🚀 Run command in container
#   About to run devcontainer exec --workspace-folder /home/runner/work/wsl2/wsl2 --remote-env GITHUB_OUTPUT=/mnt/github/output --remote-env GITHUB_ENV=/mnt/github/env --remote-env GITHUB_PATH=/mnt/github/path --remote-env GITHUB_STEP_SUMMARY=/mnt/github/step-summary bash -c pwd
#   /workspaces/wsl2/ansible
          
#           runCmd: ls -al

# 🚀 Run command in container
# About to run devcontainer exec --workspace-folder /home/runner/work/wsl2/wsl2 --remote-env GITHUB_OUTPUT=/mnt/github/output --remote-env GITHUB_ENV=/mnt/github/env --remote-env GITHUB_PATH=/mnt/github/path --remote-env GITHUB_STEP_SUMMARY=/mnt/github/step-summary bash -c ls -al
# total 76
# drwxr-xr-x    5 1001     127           4096 Sep 18 11:41 .
# drwxr-xr-x    6 1001     127           4096 Sep 18 11:41 ..
# -rw-r--r--    1 1001     127            478 Sep 18 11:41 .env
# -rw-r--r--    1 1001     127           4048 Sep 18 11:41 Dockerfile-locale-nossh
# -rw-r--r--    1 1001     127          19945 Sep 18 11:41 README.md
# -rw-r--r--    1 1001     127            262 Sep 18 11:41 ansible.cfg
# -rw-r--r--    1 1001     127           1775 Sep 18 11:41 docker-compose-locale copy.yml
# -rw-r--r--    1 1001     127           1014 Sep 18 11:41 docker-compose-locale-ssh-test.yml
# -rw-r--r--    1 1001     127           1469 Sep 18 11:41 docker-compose-locale.yml
# drwxr-xr-x    2 1001     127           4096 Sep 18 11:41 files
# drwxr-xr-x    2 1001     127           4096 Sep 18 11:41 group_vars
# -rw-r--r--    1 1001     127            344 Sep 18 11:41 inventory.ini
# -rw-r--r--    1 1001     127           3233 Sep 18 11:41 main.yml
# -rw-r--r--    1 1001     127            228 Sep 18 11:41 requirements.yml
# drwxr-xr-x    2 1001     127           4096 Sep 18 11:41 vars